=== weijiancai/fly/autoproject/src/test/resources/fly-framework.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT fly (dbms*)>

<!ELEMENT dbms (schema*)>
<!ATTLIST dbms
    driverClass        CDATA #IMPLIED
    host               CDATA #IMPLIED
    port               CDATA #IMPLIED
    userName           CDATA #IMPLIED
    password           CDATA #IMPLIED
    type               (mysql | oracle) "mysql"
>

<!ELEMENT schema (table)>
<!ATTLIST schema
    name               CDATA #IMPLIED
>

<!ELEMENT table (column*, sql*)>
<!ATTLIST table
    name               CDATA #IMPLIED
    comment            CDATA #IMPLIED
>

<!ELEMENT column ()>
<!ATTLIST column
    name               CDATA #IMPLIED
    comment            CDATA #IMPLIED
>

<!ELEMENT sql (#PCDATA)>


<fly>
    <dbms>
        <schema name="crm">
            <table>
                <column pk="" fk=""></column>
            </table>
        </schema>
    </dbms>

    <project dbms="">
        <class table="">
            <field col=""/>
        </class>
    </project>
</fly>

=== weijiancai/fly/autoproject/src/test/resources/fly.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE fly SYSTEM "fly-framework.dtd">

<fly>
    <dbms driverClass="com.mysql.jdbc.Driver" host="127.0.0.1" port="3306" userName="crm" password="123" type="mysql">
        <schema name="crm">
            <table name="cgdd" comment="采购订单">
                <column name="id" comment="主键"/>
            </table>
        </schema>

        <schema name="yuncrm">
            <table>
                <sql>
                    <![CDATA[
                        create table sys_dz_category
                        (
                        category_id          varbinary(32) not null comment '类别内码',
                        category_name        varchar(64) not null comment '类别名称',
                        is_valid             int(1) comment '是否有效',
                        sort_num             int(11) comment '排序号',
                        input_date           datetime comment '录入时间',
                        primary key (category_id)
                        );

                        alter table sys_dz_category comment '字典类别';
                    ]]>
                </sql>
                <column/>
            </table>
        </schema>
    </dbms>
</fly>
